"""
Landscape types in GEE
https://zenodo.org/records/4723921

30: "Mosaic cropland (>50%) / natural vegetation (tree, shrub, herbaceous cover) (<50%)",
40: "Mosaic natural vegetation (tree, shrub, herbaceous cover) (>50%) / cropland (<50%)",
50: "Tree cover, broadleaved, evergreen, closed to open (>15%)",
80: "Tree cover, needleleaved, deciduous, closed to open (>15%)",
121: "Evergreen shrubland",
90: "Tree cover, mixed leaf type (broadleaved and needleleaved)",
"""
# TODO Update in accordance to the latest documentation
landscape_types = {
    10: 'Cropland, rainfed',
    11: 'Herbaceous cover',
    12: 'Tree or shrub cover',
    20: 'Cropland, irrigated or post-flooding',
    30: 'Herbaceous vegetation',
    40: 'Cultivated land',
    50: 'Urban area',
    60: 'Tree cover, broadleaved, deciduous, closed to open (>15%)',
    61: 'Tree cover, broadleaved, deciduous, closed (>40%)',
    62: 'Tree cover, broadleaved, deciduous, open (15-40%)',
    70: 'Tree cover, needleleaved, evergreen, closed to open (>15%)',
    71: 'Tree cover, needleleaved, evergreen, closed (>40%)',
    72: 'Tree cover, needleleaved, evergreen, open (15-40%)',
    80: 'Water bodies',
    81: 'Tree cover, needleleaved, deciduous, closed (>40%)',
    82: 'Tree cover, needleleaved, deciduous, open (15-40%)',
    90: 'Herbaceous wetland',
    100: 'Mosaic tree and shrub (>50%) / herbaceous cover (<50%)',
    110: 'Mosaic herbaceous cover (>50%) / tree and shrub (<50%)',
    111: 'Evergreen forest',
    114: 'Grassland',
    115: 'Shrubland',
    116: 'Bare land',
    120: 'Shrubland',
    121: 'Permanent snow/ice',
    122: 'Deciduous shrubland',
    124: 'Deciduous needleleaf forest',
    125: 'Mixed forest',
    126: 'Non-forested wetland',
    130: 'Grassland',
    140: 'Lichens and mosses',
    150: 'Sparse vegetation (tree, shrub, herbaceous cover) (<15%)',
    151: 'Sparse tree (<15%)',
    152: 'Sparse shrub (<15%)',
    153: 'Sparse herbaceous cover (<15%)',
    160: 'Tree cover, flooded, fresh or brackish water',
    170: 'Tree cover, flooded, saline water',
    180: 'Shrub or herbaceous cover, flooded, fresh/saline/brackish water',
    190: 'Urban areas',
    200: 'Bare areas',
    201: 'Consolidated bare areas',
    202: 'Unconsolidated bare areas',
    210: 'Water bodies',
    220: 'Permanent snow and ice'
}

COPERNICUS_CROP_CLASS_ID = 40
